apiVersion: 1

contactPoints:
  - orgId: 1
    name: ops-email
    receivers:
      - uid: ops_email_uid
        type: email
        settings:
          addresses: alerts@gatewayz.ai, ops@gatewayz.ai
          singleEmail: false
        disableResolveMessage: false
    provenance: Grafana

  - orgId: 1
    name: critical-email
    receivers:
      - uid: critical_email_uid
        type: email
        settings:
          addresses: on-call@gatewayz.ai
          singleEmail: false
        disableResolveMessage: false
    provenance: Grafana

  - orgId: 1
    name: dev-team-email
    receivers:
      - uid: dev_team_uid
        type: email
        settings:
          addresses: dev@gatewayz.ai
          singleEmail: false
        disableResolveMessage: false
    provenance: Grafana
