apiVersion: 1

datasources:
  - name: alertmanager
    type: alertmanager
    uid: alertmanager
    access: proxy
    orgId: 1
    url: http://alertmanager.railway.internal:9093
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
    editable: false
