apiVersion: 1

datasources:
  - name: JSON API
    uid: grafana_json_api
    type: grafana-simple-json-datasource
    access: proxy
    url: ${API_BASE_URL:-https://api.gatewayz.ai}
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      tlsSkipVerify: false
    version: 1
